---
- hosts: localhost
  gather_facts: no
  become: True
  tasks:  
    - name: build docker app image
      ansible.builtin.command:
        cmd: docker build -t project-app:latest .
   
    - name: tag docker app image
      ansible.builtin.command:
        cmd: project-app:latest blickng/project-app-prod:latest

    - name: login to docker repo
      ansible.builtin.command:
        cmd: docker login -u blickng -p $dockerpassword

    - name: push image to docker repo
      ansible.builtin.command:
        cmd: docker push blickng/project-app-prod:latest

- hosts: tag_Name_prod_app_server
  become: True
  tasks:
    - name: pull and run prod app docker image
      ansible.builtin.command:
        cmd: docker run -d -p 8080:8080 -e loginname=myname -e loginpass=mypass -e api_key=xxxxxxxx --name project-app-prod blickng/project-app-prod:latest

